spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/demo
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
